// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO40dnqsab1HI9FGjsok0PBcevZ1qoQKw',
    appId: '1:612372132799:web:4fac7bcefc30047711670a',
    messagingSenderId: '612372132799',
    projectId: 'ultimate360s',
    authDomain: 'ultimate360s.firebaseapp.com',
    storageBucket: 'ultimate360s.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO4roLsHi3zOqN5B4HC5SPcG-sjLNlPl4',
    appId: '1:612372132799:android:2a06bb00ffb9740a11670a',
    messagingSenderId: '612372132799',
    projectId: 'ultimate360s',
    storageBucket: 'ultimate360s.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUIt6UrFmX5jQe_f7lu3_oILnmgbOyDo',
    appId: '1:612372132799:ios:ccad3df12eb1faf011670a',
    messagingSenderId: '612372132799',
    projectId: 'ultimate360s',
    storageBucket: 'ultimate360s.firebasestorage.app',
    iosBundleId: 'com.example.ultimate360s',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpUIt6UrFmX5jQe_f7lu3_oILnmgbOyDo',
    appId: '1:612372132799:ios:ccad3df12eb1faf011670a',
    messagingSenderId: '612372132799',
    projectId: 'ultimate360s',
    storageBucket: 'ultimate360s.firebasestorage.app',
    iosBundleId: 'com.example.ultimate360s',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO40dnqsab1HI9FGjsok0PBcevZ1qoQKw',
    appId: '1:612372132799:web:7ee148c712a22ba311670a',
    messagingSenderId: '612372132799',
    projectId: 'ultimate360s',
    authDomain: 'ultimate360s.firebaseapp.com',
    storageBucket: 'ultimate360s.firebasestorage.app',
  );
}
